version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    environment:
      - TZ=UTC 
      - PORT=4000
      - DSN=web:pass@tcp(mysql:3306)/snippetbox?parseTime=true
      - USE_PROXY=true
    volumes:
      - ./tls:/app/tls
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    restart: unless-stopped
